#1.set primary key
use database tojo_data;
create or replace table SALES_DATA_FINAL
(
 ORDER_ID VARCHAR(30) PRIMARY KEY,
 ORDER_DATE DATE,
 SHIP_DATE DATE,
 SHIP_MODE VARCHAR(30),
 CUSTOMER_NAME VARCHAR(60),
 SEGMENT VARCHAR(60),
 STATE VARCHAR(60),
 COUNTRY VARCHAR(60),
 MARKET VARCHAR(60),
 REGION VARCHAR(60),
 PRODUCT_ID VARCHAR(60),
 CATEGORY VARCHAR(60),
 SUB_CATEGORY VARCHAR(60),
 PRODUCT_NAME VARCHAR2(500),
 SALES number(10,0),
 QUANTITY int,
 DISCOUNT FLOAT,
 PROFIT float,
 SHIPPING_COST FLOAT,
 ORDER_PRIORITY VARCHAR2(100),
 YEAR VARCHAR(20)
 );
 
 
 SELECT * FROM SALES_DATA_FINAL;
 DESCRIBE TABLE SALES_DATA_FINAL;
 #drop the primary key
 ALTER TABLE SALES_DATA_FINAL
 DROP PRIMARY KEY;
 #set a new primary key 
 ALTER TABLE SALES_DATA_FINAL
 ADD PRIMARY KEY(ORDER_DATE);
 
 
 #2.CHECK THE ORDER DATE AND SHIP DATE TYPE AND THINK IN WHICH DATA TYPE YOU HAVE TO CHANGE.
 describe table sales_data_final;
 #its alreay in correct data type.
 

#3
SELECT DISTINCT ORDER_DATE FROM SALES_DATA_FINAL WHERE LIKE ('%-') ;
 
#4.FLAG ,IF DISCOUNT IS GREATER THEN 0 THEN  YES ELSE FALSE AND PUT IT IN NEW COLUMN FRO EVERY ORDER ID.
SELECT *,
CASE
    WHEN DISCOUNT > 0 THEN 'YES'
    ELSE 'NO'
    END AS DISCOUNT_STATUS
    FROM SALES_DATA_FINAL;
    

#6.FIND OUT HOW MUCH DAYS TAKEN FOR EACH ORDER TO PROCESS FOR THE SHIPMENT FOR EVERY ORDER ID.
SELECT *,
DATEDIFF('DAY',ORDER_DATE,SHIP_DATE) AS DAY_PASSES FROM SALES_DATA_FINAL;



#7. FLAG THE PROCESS DAY AS BY RATING IF IT TAKES LESS OR EQUAL 3  DAYS MAKE 5,
#LESS OR EQUAL THAN 6 DAYS BUT MORE THAN 3 MAKE 4,LESS THAN 10 BUT MORE THAN 6 MAKE 3,MORE THAN 10 MAKE IT 2 FOR EVERY ORDER ID.
Select *,                
Case
    When DATEDIFF('DAY',ORDER_DATE,SHIP_DATE) <= 3 Then 5
    When DATEDIFF('DAY',ORDER_DATE,SHIP_DATE) > 3 and DATEDIFF('DAY',ORDER_DATE,SHIP_DATE) <=6  Then 4
    When DATEDIFF('DAY',ORDER_DATE,SHIP_DATE) > 6 and DATEDIFF('DAY',ORDER_DATE,SHIP_DATE) <=10  Then 3
    Else 2
End As Rating
From Sales_Data_Final;




